
# YOLOv5 ğŸš€ by Ultralytics, GPL-3.0 license
# Example usage: python yolov5/segment/train.py --data configs/yolo_data_config.yaml
# parent
# â”œâ”€â”€ yolov5
# â””â”€â”€ datasets
#     â””â”€â”€ coco128-seg  â† downloads here (7 MB)


# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: data  # dataset root dir
train: my_train  # train images (relative to 'path')
val: my_val  # val images (relative to 'path')
test: my_test # test images (optional)

# Classes
names:
  0: cell